# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_median_cpp <- function(x, B, conf) {
    .Call(`_RcppBootstrap_bootstrap_median_cpp`, x, B, conf)
}

